import { Category, Level, ValidTag } from "../../../db";
import type { QuestionForCategoryAndLevel } from "../../../lib/types";

export const mid: QuestionForCategoryAndLevel<
    typeof Category.enum.databases,
    typeof Level.enum.mid
>[] = [
    // Database General
    {
        text: "What database would you use and why? How do you decide?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum["database-design"]],
        answers: [],
    },
    {
        text: "What is the difference between SQL and NoSQL databases?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.sql, ValidTag.enum.mongodb],
        answers: [],
    },
    {
        text: "What are ACID properties and why do they matter?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.acid, ValidTag.enum.transactions],
        answers: [],
    },
    {
        text: "What is the CAP theorem?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum["cap-theorem"]],
        answers: [],
    },
    {
        text: "What is the difference between horizontal and vertical scaling for databases?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.scalability, ValidTag.enum.sharding],
        answers: [],
    },
    {
        text: "What is database sharding and when would you use it?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.sharding, ValidTag.enum.scalability],
        answers: [],
    },
    {
        text: "What is replication and what are the different strategies?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.replication],
        answers: [],
    },
    {
        text: "What is connection pooling and why is it important?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What are database transactions?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.transactions],
        answers: [],
    },
    {
        text: "What is the difference between optimistic and pessimistic locking?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.concurrency],
        answers: [],
    },
    {
        text: "What is a deadlock and how do you prevent it?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.deadlocks, ValidTag.enum.concurrency],
        answers: [],
    },

    // SQL and PostgreSQL
    {
        text: "What is normalization and when would you denormalize?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.sql, ValidTag.enum.normalization, ValidTag.enum.denormalization, ValidTag.enum["database-design"]],
        answers: [],
    },
    {
        text: "What are joins and what are the different types?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.sql, ValidTag.enum.joins],
        answers: [],
    },
    {
        text: "What are indexes and how do they work?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.sql, ValidTag.enum.indexing],
        answers: [],
    },
    {
        text: "What is the difference between a clustered and non-clustered index?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.sql, ValidTag.enum.indexing],
        answers: [],
    },
    {
        text: "What are some indexing strategies you would use and why?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.sql, ValidTag.enum.indexing, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What is a composite index and when would you use it?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.sql, ValidTag.enum.indexing],
        answers: [],
    },
    {
        text: "What is query optimization and how do you read an execution plan?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.sql, ValidTag.enum["query-optimization"], ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What are views and materialized views?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.sql],
        answers: [],
    },
    {
        text: "What are stored procedures and triggers?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.sql],
        answers: [],
    },
    {
        text: "What are CTEs (Common Table Expressions)?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.sql],
        answers: [],
    },
    {
        text: "What are window functions?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.sql],
        answers: [],
    },
    {
        text: "What is the difference between WHERE and HAVING?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.sql],
        answers: [],
    },
    {
        text: "What are constraints and what types are there?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.sql],
        answers: [],
    },
    {
        text: "What is the difference between DELETE, TRUNCATE, and DROP?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.sql],
        answers: [],
    },
    {
        text: "What are database migrations and how do you manage them?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.migrations],
        answers: [],
    },
    {
        text: "What is PostgreSQL's JSONB and when would you use it?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.postgresql],
        answers: [],
    },
    {
        text: "What are PostgreSQL extensions?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.postgresql],
        answers: [],
    },
    {
        text: "What is full-text search in PostgreSQL?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.postgresql],
        answers: [],
    },

    // MongoDB
    {
        text: "What is MongoDB and when would you choose it over SQL?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.mongodb, ValidTag.enum.sql],
        answers: [],
    },
    {
        text: "What are documents and collections?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.mongodb],
        answers: [],
    },
    {
        text: "What is the aggregation pipeline?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.mongodb, ValidTag.enum.aggregation],
        answers: [],
    },
    {
        text: "How do you model relationships in MongoDB?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.mongodb, ValidTag.enum["database-design"]],
        answers: [],
    },
    {
        text: "What are indexes in MongoDB and how do they differ from SQL?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.mongodb, ValidTag.enum.indexing],
        answers: [],
    },
    {
        text: "What is Mongoose and what problems does it solve?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.mongoose, ValidTag.enum.mongodb],
        answers: [],
    },
    {
        text: "What are Mongoose schemas and models?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.mongoose],
        answers: [],
    },
    {
        text: "What are Mongoose middleware (pre and post hooks)?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.mongoose],
        answers: [],
    },
    {
        text: "What are virtuals in Mongoose?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.mongoose],
        answers: [],
    },
    {
        text: "How do you handle transactions in MongoDB?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.mongodb, ValidTag.enum.transactions],
        answers: [],
    },
    {
        text: "What is the difference between embedding and referencing?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.mongodb, ValidTag.enum["database-design"]],
        answers: [],
    },
    {
        text: "What are MongoDB operators?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.mongodb],
        answers: [],
    },
    {
        text: "How do you handle migrations in MongoDB?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.mongodb, ValidTag.enum.migrations],
        answers: [],
    },

    // Prisma
    {
        text: "What is Prisma and how does it differ from other ORMs?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.prisma],
        answers: [],
    },
    {
        text: "What is the Prisma schema and how do you define models?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.prisma],
        answers: [],
    },
    {
        text: "What is Prisma Client and how is it generated?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.prisma],
        answers: [],
    },
    {
        text: "How do you handle migrations in Prisma?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.prisma, ValidTag.enum.migrations],
        answers: [],
    },
    {
        text: "What are relations in Prisma and how do you query them?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.prisma],
        answers: [],
    },
    {
        text: "What is Prisma Studio?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.prisma],
        answers: [],
    },
    {
        text: "How do you handle raw SQL queries in Prisma?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.prisma, ValidTag.enum.sql],
        answers: [],
    },
    {
        text: "What are Prisma middleware?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.prisma],
        answers: [],
    },
    {
        text: "How do you handle soft deletes in Prisma?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.prisma],
        answers: [],
    },
    {
        text: "What is the difference between findUnique, findFirst, and findMany?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.prisma],
        answers: [],
    },
    {
        text: "How do you handle transactions in Prisma?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.prisma, ValidTag.enum.transactions],
        answers: [],
    },
    {
        text: "What are nested writes in Prisma?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.prisma],
        answers: [],
    },

    // Supabase
    {
        text: "What is Supabase and how does it differ from Firebase?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.supabase],
        answers: [],
    },
    {
        text: "What is Supabase Auth and how do you implement authentication?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.supabase, ValidTag.enum.auth],
        answers: [],
    },
    {
        text: "What are Row Level Security policies?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.supabase, ValidTag.enum.rbac, ValidTag.enum.security],
        answers: [],
    },
    {
        text: "How do you use Supabase real-time subscriptions?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.supabase, ValidTag.enum["pub-sub"]],
        answers: [],
    },
    {
        text: "What is Supabase Storage and how do you handle file uploads?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.supabase],
        answers: [],
    },
    {
        text: "How do you call Supabase Edge Functions?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.supabase],
        answers: [],
    },
    {
        text: "What are Supabase database functions?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.supabase],
        answers: [],
    },
    {
        text: "If you use Supabase, at what point would you switch to something else, what would it be, and why?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.supabase],
        answers: [],
    },
    {
        text: "How do you handle migrations in Supabase?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.supabase, ValidTag.enum.migrations],
        answers: [],
    },
    {
        text: "What are the limitations of Supabase?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.supabase],
        answers: [],
    },

    // Redis
    {
        text: "What is Redis and what are its primary use cases?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.redis, ValidTag.enum.caching],
        answers: [],
    },
    {
        text: "What data structures does Redis support?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.redis],
        answers: [],
    },
    {
        text: "What is Redis pub/sub and when would you use it?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.redis, ValidTag.enum["pub-sub"]],
        answers: [],
    },
    {
        text: "How do you implement caching with Redis?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.redis, ValidTag.enum.caching],
        answers: [],
    },
    {
        text: "What are Redis transactions?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.redis, ValidTag.enum.transactions],
        answers: [],
    },
    {
        text: "What is Redis Cluster and how does it work?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.redis, ValidTag.enum.scalability],
        answers: [],
    },
    {
        text: "What is Redis Sentinel?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.redis, ValidTag.enum["high-availability"]],
        answers: [],
    },
    {
        text: "How do you handle cache invalidation with Redis?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.redis, ValidTag.enum["cache-invalidation"]],
        answers: [],
    },
    {
        text: "What is Redis persistence and what are the options (RDB vs AOF)?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.redis],
        answers: [],
    },
    {
        text: "What are Redis Streams?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.redis],
        answers: [],
    },
    {
        text: "How do you handle session storage with Redis?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.redis, ValidTag.enum["session-management"]],
        answers: [],
    },
    {
        text: "What is Redis Lua scripting and when would you use it?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.redis],
        answers: [],
    },
    {
        text: "What are Redis TTL and expiration strategies?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.redis, ValidTag.enum.caching],
        answers: [],
    },

    // Caching
    {
        text: "What are cache invalidation strategies and what are the tradeoffs?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.caching, ValidTag.enum["cache-invalidation"]],
        answers: [],
    },
    {
        text: "What is the difference between write-through, write-behind, and write-around caching?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.caching, ValidTag.enum["cache-strategies"]],
        answers: [],
    },
    {
        text: "What is cache stampede and how do you prevent it?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.caching],
        answers: [],
    },
    {
        text: "What is the difference between in-memory cache and distributed cache?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.caching],
        answers: [],
    },
    {
        text: "When would you use Redis vs Memcached?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.redis, ValidTag.enum.caching],
        answers: [],
    },
    {
        text: "What are caching headers and how do they work?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.caching, ValidTag.enum["cache-control"]],
        answers: [],
    },
    {
        text: "What is stale-while-revalidate?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.caching],
        answers: [],
    },
    {
        text: "How do you decide what to cache and for how long?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.caching],
        answers: [],
    },

    // CDN
    {
        text: "What is a CDN and how does it work?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.cdn],
        answers: [],
    },
    {
        text: "What is the difference between a push CDN and a pull CDN?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.cdn],
        answers: [],
    },
    {
        text: "How do you handle cache invalidation with a CDN?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.cdn, ValidTag.enum["cache-invalidation"]],
        answers: [],
    },
    {
        text: "What are edge locations?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.cdn],
        answers: [],
    },
    {
        text: "How do you configure CDN caching rules?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.cdn, ValidTag.enum.caching],
        answers: [],
    },
    {
        text: "What is origin shielding?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.cdn],
        answers: [],
    },
    {
        text: "What are the tradeoffs between different CDN providers?",
        level: Level.enum.mid,
        category: Category.enum.databases,
        tags: [ValidTag.enum.cdn],
        answers: [],
    },
];
