import { Category, Level, ValidTag } from "../../../db";
import type { QuestionForCategoryAndLevel } from "../../../lib/types";

export const mid: QuestionForCategoryAndLevel<
    typeof Category.enum.devops,
    typeof Level.enum.mid
>[] = [
    // AWS General
    {
        text: "What are the core AWS services and when would you use each?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws],
        answers: [],
    },
    {
        text: "What is the AWS shared responsibility model?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What are AWS regions and availability zones?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws],
        answers: [],
    },
    {
        text: "What is VPC and how do you configure networking?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.vpc],
        answers: [],
    },
    {
        text: "What are security groups and NACLs?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.vpc, ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What is AWS CloudFormation and infrastructure as code?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws],
        answers: [],
    },
    {
        text: "What is the difference between CloudFormation and Terraform?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws],
        answers: [],
    },

    // EC2
    {
        text: "What is EC2 and how do instance types work?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.ec2],
        answers: [],
    },
    {
        text: "What are EC2 pricing models (on-demand, reserved, spot)?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.ec2],
        answers: [],
    },
    {
        text: "What is an AMI?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.ec2],
        answers: [],
    },
    {
        text: "What are EC2 placement groups?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.ec2],
        answers: [],
    },
    {
        text: "What is auto-scaling and how do you configure it?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.ec2, ValidTag.enum.scalability],
        answers: [],
    },
    {
        text: "What are launch templates?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.ec2],
        answers: [],
    },
    {
        text: "How do you handle EC2 instance storage?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.ec2],
        answers: [],
    },

    // S3
    {
        text: "What is S3 and what are its use cases?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.s3],
        answers: [],
    },
    {
        text: "What are S3 storage classes?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.s3],
        answers: [],
    },
    {
        text: "What are S3 bucket policies vs IAM policies?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.s3, ValidTag.enum.iam],
        answers: [],
    },
    {
        text: "What is S3 versioning?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.s3],
        answers: [],
    },
    {
        text: "What is S3 lifecycle management?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.s3],
        answers: [],
    },
    {
        text: "How do you configure S3 for static website hosting?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.s3],
        answers: [],
    },
    {
        text: "What are presigned URLs and when would you use them?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.s3],
        answers: [],
    },
    {
        text: "What is S3 Transfer Acceleration?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.s3],
        answers: [],
    },
    {
        text: "How do you handle cross-region replication?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.s3],
        answers: [],
    },
    {
        text: "What is the difference between S3 and EBS?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.s3],
        answers: [],
    },

    // Lambda
    {
        text: "What is AWS Lambda?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.lambda, ValidTag.enum.serverless],
        answers: [],
    },
    {
        text: "What are Lambda triggers?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.lambda],
        answers: [],
    },
    {
        text: "How do you handle Lambda cold starts?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.lambda, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What are Lambda layers?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.lambda],
        answers: [],
    },
    {
        text: "How do you configure Lambda memory and timeout?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.lambda],
        answers: [],
    },
    {
        text: "What is API Gateway and how does it integrate with Lambda?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.lambda],
        answers: [],
    },
    {
        text: "What are Lambda environment variables and secrets management?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.lambda],
        answers: [],
    },
    {
        text: "How do you monitor Lambda functions?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.lambda, ValidTag.enum.monitoring],
        answers: [],
    },
    {
        text: "What is Lambda@Edge?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.lambda],
        answers: [],
    },

    // IAM
    {
        text: "What is IAM and how does it work?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.iam, ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What are IAM users, groups, and roles?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.iam],
        answers: [],
    },
    {
        text: "What are IAM policies and how do you write them?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.iam],
        answers: [],
    },
    {
        text: "What is the principle of least privilege in IAM?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.iam, ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What are IAM conditions?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.iam],
        answers: [],
    },
    {
        text: "What is cross-account access?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.iam],
        answers: [],
    },
    {
        text: "What are service-linked roles?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.iam],
        answers: [],
    },
    {
        text: "What is the difference between identity-based and resource-based policies?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.iam],
        answers: [],
    },
    {
        text: "How do you audit IAM permissions?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.iam],
        answers: [],
    },

    // RDS
    {
        text: "What is RDS and how does it differ from self-managed databases?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.rds],
        answers: [],
    },
    {
        text: "What are RDS Multi-AZ deployments?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.rds, ValidTag.enum["high-availability"]],
        answers: [],
    },
    {
        text: "What are RDS read replicas?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.rds, ValidTag.enum.scalability],
        answers: [],
    },
    {
        text: "How does RDS backup and recovery work?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.rds],
        answers: [],
    },
    {
        text: "What is RDS Performance Insights?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.rds, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "How do you scale RDS?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.rds, ValidTag.enum.scalability],
        answers: [],
    },
    {
        text: "What is Amazon Aurora and how does it differ from RDS?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.rds],
        answers: [],
    },

    // Cognito
    {
        text: "What is AWS Cognito?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.cognito, ValidTag.enum.auth],
        answers: [],
    },
    {
        text: "What are user pools vs identity pools?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.cognito],
        answers: [],
    },
    {
        text: "How does Cognito authentication flow work?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.cognito, ValidTag.enum.auth],
        answers: [],
    },
    {
        text: "What are Cognito triggers?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.cognito],
        answers: [],
    },
    {
        text: "How do you implement social login with Cognito?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.cognito, ValidTag.enum.oauth],
        answers: [],
    },
    {
        text: "What is Cognito hosted UI?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.cognito],
        answers: [],
    },
    {
        text: "How do you customize Cognito emails and SMS?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.cognito],
        answers: [],
    },

    // Other AWS
    {
        text: "What is CloudFront and how do you configure it?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.cloudfront, ValidTag.enum.cdn],
        answers: [],
    },
    {
        text: "What is Route 53 and how does DNS work?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.route53],
        answers: [],
    },
    {
        text: "What is SQS and when would you use it?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.sqs, ValidTag.enum["message-queues"]],
        answers: [],
    },
    {
        text: "What is SNS and how does it differ from SQS?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.sns, ValidTag.enum.sqs],
        answers: [],
    },
    {
        text: "What is EventBridge?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum["event-driven"]],
        answers: [],
    },
    {
        text: "What is DynamoDB and when would you choose it?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.dynamodb],
        answers: [],
    },
    {
        text: "What is ElastiCache?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.elasticache, ValidTag.enum.caching],
        answers: [],
    },
    {
        text: "What are CloudWatch metrics, logs, and alarms?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.cloudwatch, ValidTag.enum.monitoring],
        answers: [],
    },
    {
        text: "What is AWS Secrets Manager vs Parameter Store?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.aws, ValidTag.enum.security],
        answers: [],
    },

    // GCP
    {
        text: "What are the core GCP services and how do they map to AWS?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.gcp, ValidTag.enum.aws],
        answers: [],
    },
    {
        text: "What is Cloud Run?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.gcp, ValidTag.enum["cloud-run"]],
        answers: [],
    },
    {
        text: "What is Cloud Functions?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.gcp, ValidTag.enum["cloud-functions"]],
        answers: [],
    },
    {
        text: "What is Cloud Storage?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.gcp, ValidTag.enum["cloud-storage"]],
        answers: [],
    },
    {
        text: "What is Cloud SQL vs Cloud Spanner?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.gcp],
        answers: [],
    },
    {
        text: "What is BigQuery?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.gcp],
        answers: [],
    },
    {
        text: "What is Firebase and how does it integrate with GCP?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.gcp, ValidTag.enum.firestore],
        answers: [],
    },
    {
        text: "What is Cloud IAM?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.gcp, ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What is Pub/Sub?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.gcp, ValidTag.enum["pub-sub"]],
        answers: [],
    },

    // Docker
    {
        text: "What is Docker and what problems does it solve?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.docker, ValidTag.enum.containers],
        answers: [],
    },
    {
        text: "What is a Docker image vs a container?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.docker, ValidTag.enum.images, ValidTag.enum.containers],
        answers: [],
    },
    {
        text: "What is a Dockerfile and how do you write one?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.docker, ValidTag.enum.dockerfile],
        answers: [],
    },
    {
        text: "What is the difference between CMD and ENTRYPOINT?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.docker, ValidTag.enum.dockerfile],
        answers: [],
    },
    {
        text: "What are Docker layers and how does caching work?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.docker],
        answers: [],
    },
    {
        text: "What is the difference between COPY and ADD?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.docker, ValidTag.enum.dockerfile],
        answers: [],
    },
    {
        text: "What is a multi-stage build and why would you use it?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.docker, ValidTag.enum.dockerfile],
        answers: [],
    },
    {
        text: "What are Docker volumes and how do they work?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.docker, ValidTag.enum.volumes],
        answers: [],
    },
    {
        text: "What is Docker networking?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.docker, ValidTag.enum.networks],
        answers: [],
    },
    {
        text: "What is Docker Compose?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.docker, ValidTag.enum["docker-compose"]],
        answers: [],
    },
    {
        text: "How do you optimize Docker image size?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.docker],
        answers: [],
    },
    {
        text: "What is the difference between docker run and docker exec?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.docker],
        answers: [],
    },
    {
        text: "What are Docker health checks?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.docker],
        answers: [],
    },
    {
        text: "What is the difference between containers and virtual machines?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.docker, ValidTag.enum.containers],
        answers: [],
    },
    {
        text: "How do you handle secrets in Docker?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.docker, ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What is a Docker registry?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.docker],
        answers: [],
    },

    // Kubernetes
    {
        text: "What is Kubernetes and what problems does it solve?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.kubernetes],
        answers: [],
    },
    {
        text: "What is the Kubernetes architecture (control plane, nodes)?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.kubernetes],
        answers: [],
    },
    {
        text: "What are pods and why are they the smallest deployable unit?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.kubernetes, ValidTag.enum.pods],
        answers: [],
    },
    {
        text: "What are deployments and how do they manage pods?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.kubernetes, ValidTag.enum.deployments],
        answers: [],
    },
    {
        text: "What are services and what types are there (ClusterIP, NodePort, LoadBalancer)?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.kubernetes, ValidTag.enum.services],
        answers: [],
    },
    {
        text: "What are namespaces?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.kubernetes],
        answers: [],
    },
    {
        text: "What is a ReplicaSet?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.kubernetes],
        answers: [],
    },
    {
        text: "What are ConfigMaps and Secrets?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.kubernetes, ValidTag.enum.configmaps, ValidTag.enum.secrets],
        answers: [],
    },
    {
        text: "What are volumes in Kubernetes and how do they differ from Docker volumes?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.kubernetes, ValidTag.enum.docker],
        answers: [],
    },
    {
        text: "What are StatefulSets and when would you use them?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.kubernetes],
        answers: [],
    },
    {
        text: "What are DaemonSets?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.kubernetes],
        answers: [],
    },
    {
        text: "What is an Ingress and how does it differ from a Service?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.kubernetes, ValidTag.enum.ingress],
        answers: [],
    },
    {
        text: "What are labels and selectors?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.kubernetes],
        answers: [],
    },
    {
        text: "What is kubectl and what are common commands?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.kubernetes],
        answers: [],
    },
    {
        text: "What are liveness and readiness probes?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.kubernetes],
        answers: [],
    },
    {
        text: "What is horizontal pod autoscaling?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.kubernetes, ValidTag.enum.scalability],
        answers: [],
    },
    {
        text: "What are resource requests and limits?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.kubernetes],
        answers: [],
    },
    {
        text: "What is a Helm chart?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.kubernetes, ValidTag.enum.helm],
        answers: [],
    },
    {
        text: "What is a Kubernetes operator?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.kubernetes],
        answers: [],
    },
    {
        text: "How do you handle rolling updates and rollbacks?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.kubernetes, ValidTag.enum["rolling-updates"]],
        answers: [],
    },
    {
        text: "What is a service mesh (Istio, Linkerd)?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.kubernetes, ValidTag.enum["service-mesh"]],
        answers: [],
    },

    // CI/CD
    {
        text: "What is CI/CD and why is it important?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum["ci-cd"]],
        answers: [],
    },
    {
        text: "What is the difference between continuous integration, continuous delivery, and continuous deployment?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum["ci-cd"]],
        answers: [],
    },
    {
        text: "What is a CI/CD pipeline and what stages does it typically have?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum["ci-cd"], ValidTag.enum.pipeline],
        answers: [],
    },
    {
        text: "How do you implement automated testing in CI/CD?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum["ci-cd"], ValidTag.enum.testing],
        answers: [],
    },
    {
        text: "What are build artifacts?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum["ci-cd"]],
        answers: [],
    },
    {
        text: "What is blue-green deployment?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum["ci-cd"], ValidTag.enum["blue-green"], ValidTag.enum["deployment-strategies"]],
        answers: [],
    },
    {
        text: "What is canary deployment?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum["ci-cd"], ValidTag.enum.canary, ValidTag.enum["deployment-strategies"]],
        answers: [],
    },
    {
        text: "What is feature flagging?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum["ci-cd"]],
        answers: [],
    },
    {
        text: "What are GitHub Actions and how do you configure them?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum["ci-cd"], ValidTag.enum["github-actions"]],
        answers: [],
    },
    {
        text: "What is the difference between GitHub Actions, Jenkins, CircleCI, and GitLab CI?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum["ci-cd"], ValidTag.enum["github-actions"], ValidTag.enum.jenkins, ValidTag.enum["gitlab-ci"]],
        answers: [],
    },
    {
        text: "How do you handle secrets in CI/CD?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum["ci-cd"], ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What is infrastructure as code in CI/CD?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum["ci-cd"]],
        answers: [],
    },
    {
        text: "How do you implement database migrations in CI/CD?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum["ci-cd"], ValidTag.enum.migrations],
        answers: [],
    },
    {
        text: "What is trunk-based development?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum["ci-cd"], ValidTag.enum.git],
        answers: [],
    },
    {
        text: "What are deployment environments (dev, staging, production)?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum["ci-cd"]],
        answers: [],
    },

    // Monitoring
    {
        text: "What is application monitoring and why is it important?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.monitoring, ValidTag.enum.observability],
        answers: [],
    },
    {
        text: "What is the difference between logging, metrics, and tracing?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.monitoring, ValidTag.enum.logging, ValidTag.enum.observability],
        answers: [],
    },
    {
        text: "What are log levels and how do you use them?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.logging],
        answers: [],
    },
    {
        text: "What is structured logging?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.logging],
        answers: [],
    },
    {
        text: "What is error tracking and how do tools like Sentry work?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum["error-tracking"], ValidTag.enum.sentry, ValidTag.enum.monitoring],
        answers: [],
    },
    {
        text: "What are performance metrics you should track?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.monitoring, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What is APM (Application Performance Monitoring)?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.monitoring, ValidTag.enum.apm],
        answers: [],
    },
    {
        text: "What is distributed tracing?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.monitoring, ValidTag.enum.observability],
        answers: [],
    },
    {
        text: "How do you implement alerting?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.monitoring],
        answers: [],
    },
    {
        text: "What is the difference between synthetic monitoring and real user monitoring?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.monitoring],
        answers: [],
    },
    {
        text: "What analytics tools do you use and how do you implement them?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.monitoring],
        answers: [],
    },
    {
        text: "What is A/B testing and how do you implement it?",
        level: Level.enum.mid,
        category: Category.enum.devops,
        tags: [ValidTag.enum.monitoring],
        answers: [],
    },
];
