import { Category, Level, ValidTag } from "../../../db";
import type { QuestionForCategoryAndLevel } from "../../../lib/types";

export const mid: QuestionForCategoryAndLevel<
    typeof Category.enum["system-design"],
    typeof Level.enum.mid
>[] = [
    // Microservices
    {
        text: "What is a microservice architecture and when would you use it?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.microservices, ValidTag.enum["system-design"]],
        answers: [],
    },
    {
        text: "What are the differences between monolithic and microservices architectures?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.microservices, ValidTag.enum["system-design"]],
        answers: [],
    },
    {
        text: "How do microservices communicate with each other?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.microservices],
        answers: [],
    },
    {
        text: "What is service discovery?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.microservices, ValidTag.enum["service-discovery"]],
        answers: [],
    },
    {
        text: "What is an API Gateway and why is it useful?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.microservices, ValidTag.enum["api-gateway"]],
        answers: [],
    },
    {
        text: "What are the benefits and challenges of microservices?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.microservices],
        answers: [],
    },
    {
        text: "What is a service mesh?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.microservices, ValidTag.enum["service-mesh"]],
        answers: [],
    },
    {
        text: "How do you handle distributed transactions in microservices?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.microservices, ValidTag.enum["distributed-transactions"]],
        answers: [],
    },
    {
        text: "What is the saga pattern?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.microservices, ValidTag.enum["saga-pattern"]],
        answers: [],
    },
    {
        text: "What is eventual consistency?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.microservices, ValidTag.enum["eventual-consistency"]],
        answers: [],
    },
    {
        text: "How do you handle versioning in microservices?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.microservices, ValidTag.enum["api-versioning"]],
        answers: [],
    },
    {
        text: "What is circuit breaking and why is it important?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.microservices, ValidTag.enum["circuit-breaker"]],
        answers: [],
    },
    {
        text: "What is the strangler fig pattern?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.microservices, ValidTag.enum["design-patterns"]],
        answers: [],
    },
    {
        text: "How do you monitor microservices?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.microservices, ValidTag.enum.monitoring],
        answers: [],
    },
    {
        text: "What is distributed tracing?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.microservices, ValidTag.enum.monitoring, ValidTag.enum.tracing],
        answers: [],
    },
    {
        text: "What are the 12-factor app principles?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.microservices, ValidTag.enum["system-design"]],
        answers: [],
    },

    // Concurrency
    {
        text: "What is a race condition?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.concurrency],
        answers: [],
    },
    {
        text: "What is deadlock and how do you prevent it?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.concurrency],
        answers: [],
    },
    {
        text: "What is the difference between concurrency and parallelism?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.concurrency],
        answers: [],
    },
    {
        text: "What are the different ways to handle concurrency in JavaScript?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.concurrency, ValidTag.enum.javascript],
        answers: [],
    },
    {
        text: "What is optimistic vs pessimistic locking?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.concurrency, ValidTag.enum.databases],
        answers: [],
    },
    {
        text: "What is a mutex vs semaphore?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.concurrency],
        answers: [],
    },
    {
        text: "What is the actor model?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.concurrency, ValidTag.enum["design-patterns"]],
        answers: [],
    },
    {
        text: "What are Web Workers and when would you use them?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum.concurrency, ValidTag.enum.javascript, ValidTag.enum["web-workers"]],
        answers: [],
    },

    // Architecture/Design Patterns
    {
        text: "What is the repository pattern?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum["design-patterns"]],
        answers: [],
    },
    {
        text: "What is dependency injection and why is it useful?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum["design-patterns"], ValidTag.enum["dependency-injection"]],
        answers: [],
    },
    {
        text: "What is SOLID principles?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum["design-patterns"], ValidTag.enum.solid],
        answers: [],
    },
    {
        text: "What is the difference between composition and inheritance?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum["design-patterns"], ValidTag.enum.oop],
        answers: [],
    },
    {
        text: "What is the factory pattern?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum["design-patterns"]],
        answers: [],
    },
    {
        text: "What is the singleton pattern and when would you use it?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum["design-patterns"]],
        answers: [],
    },
    {
        text: "What is the observer pattern?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum["design-patterns"]],
        answers: [],
    },
    {
        text: "What is the adapter pattern?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum["design-patterns"]],
        answers: [],
    },
    {
        text: "What is the decorator pattern?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum["design-patterns"]],
        answers: [],
    },
    {
        text: "What is the strategy pattern?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum["design-patterns"]],
        answers: [],
    },
    {
        text: "What is the command pattern?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum["design-patterns"]],
        answers: [],
    },
    {
        text: "What is CQRS?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum["design-patterns"], ValidTag.enum.cqrs],
        answers: [],
    },
    {
        text: "What is event sourcing?",
        level: Level.enum.mid,
        category: Category.enum["system-design"],
        tags: [ValidTag.enum["design-patterns"], ValidTag.enum["event-sourcing"]],
        answers: [],
    },
];
