import { z } from "zod";

// Level enum values for question difficulty
export const levels = [
    "junior",
    "junior-advanced",
    "mid",
    "mid-advanced",
    "senior",
    "senior-advanced",
] as const;

export const Level = z.enum(levels);
export const _Level = Level.enum;

export type Level = z.infer<typeof Level>;

// Category enum values for question domains
export const categories = [
    "frontend",
    "backend",
    "fullstack",
    "devops",
    "databases",
    "system-design",
    "behavioral",
    "algorithms",
    "security",
] as const;

export const Category = z.enum(categories);
export const _Category = Category.enum;

export type Category = z.infer<typeof Category>;

// Predefined tags for technologies and concepts
export const validTags = [
    // JavaScript Core
    "javascript",
    "event-loop",
    "closures",
    "promises",
    "async-await",
    "prototypes",
    "this-keyword",
    "arrow-functions",
    "destructuring",
    "spread-operator",
    "modules",
    "classes",
    "template-literals",
    "symbols",
    "weakmap",
    "weakset",
    "proxies",
    "generators",
    "iterators",
    "hoisting",
    "scope",
    "var-let-const",
    "strict-mode",

    // Node.js Core
    "statefulsets",

    // TypeScript
    "typescript",
    "generics",
    "interfaces",
    "types",
    "type-guards",
    "utility-types",
    "decorators",
    "enums",
    "namespaces",
    "mapped-types",
    "conditional-types",

    // React Core
    "react",
    "jsx",
    "props",
    "state",
    "lifecycle",
    "hooks",
    "useState",
    "useEffect",
    "useContext",
    "useReducer",
    "useMemo",
    "useCallback",
    "useRef",
    "custom-hooks",
    "reconciliation",
    "virtual-dom",
    "synthetic-events",
    "fragments",
    "portals",
    "error-boundaries",
    "suspense",
    "concurrent-mode",
    "server-components",
    "rsc",
    "react-native",

    // State Management
    "redux",
    "redux-toolkit",
    "zustand",
    "context-api",
    "recoil",
    "jotai",
    "mobx",
    "tanstack-query",
    "query-keys",
    "query-cache",

    // Next.js & Routing
    "nextjs",
    "routing",
    "pages-router",
    "app-router",
    "ssr",
    "ssg",
    "isr",
    "csr",
    "middleware",
    "api-routes",
    "file-based-routing",
    "dynamic-routes",

    // HTML & CSS
    "html",
    "semantic-html",
    "css",
    "box-model",
    "flexbox",
    "grid",
    "responsive-design",
    "media-queries",
    "animations",
    "transitions",
    "preprocessors",
    "sass",
    "less",
    "tailwind",
    "css-modules",
    "styled-components",
    "css-in-js",
    "bem",

    // Accessibility & SEO
    "accessibility",
    "a11y",
    "wcag",
    "aria",
    "screen-readers",
    "keyboard-navigation",
    "focus-management",
    "seo",
    "forms",

    // Build Tools & Bundlers
    "webpack",
    "vite",
    "turbopack",
    "tree-shaking",
    "bundling",
    "code-splitting",
    "lazy-loading",

    // Backend & Node.js
    "nodejs",
    "event-emitter",
    "streams",
    "buffers",
    "child-processes",
    "cluster",
    "express",
    "middleware",
    "error-handling",
    "validation",
    "nestjs",
    "dto",
    "dependency-injection",
    "interceptors",
    "guards",
    "pipes",

    // API Technologies
    "rest-api",
    "graphql",
    "grpc",
    "protocol-buffers",
    "websockets",
    "serverless",
    "api-design",
    "api-versioning",
    "rate-limiting",
    "pagination",
    "idempotency",
    "http-methods",
    "status-codes",

    // Databases & ORMs
    "databases",
    "sql",
    "postgresql",
    "mysql",
    "mongodb",
    "mongoose",
    "redis",
    "prisma",
    "typeorm",
    "supabase",
    "database-design",
    "indexing",
    "acid",
    "cap-theorem",
    "normalization",
    "denormalization",
    "joins",
    "aggregation",
    "transactions",
    "migrations",
    "sharding",
    "replication",
    "pub-sub",
    "query-optimization",
    "n-plus-one",
    "distributed-transactions",

    // Caching & CDN
    "caching",
    "cache-invalidation",
    "cache-strategies",
    "etag",
    "cache-control",
    "cdn",

    // Authentication & Authorization
    "auth",
    "jwt",
    "refresh-tokens",
    "oauth",
    "session-management",
    "rbac",
    "authorization",

    // Security
    "security",
    "cors",
    "csrf",
    "xss",
    "sql-injection",
    "password-hashing",
    "bcrypt",

    // Testing
    "testing",
    "jest",
    "rtl",
    "tdd",
    "e2e",
    "unit-testing",
    "integration-testing",
    "mocking",
    "test-doubles",
    "matchers",
    "coverage",
    "snapshot-testing",
    "msw",

    // AWS Services
    "aws",
    "ec2",
    "s3",
    "lambda",
    "rds",
    "iam",
    "vpc",
    "cognito",
    "cloudfront",
    "route53",
    "dynamodb",
    "sqs",
    "sns",
    "elasticache",
    "ecs",
    "fargate",
    "cloudwatch",

    // GCP Services
    "gcp",
    "cloud-functions",
    "cloud-storage",
    "cloud-run",
    "firestore",

    // Docker & Containers
    "docker",
    "docker-compose",
    "dockerfile",
    "containers",
    "images",
    "volumes",
    "networks",

    // Kubernetes
    "kubernetes",
    "pods",
    "deployments",
    "services",
    "ingress",
    "configmaps",
    "secrets",
    "helm",

    // CI/CD & DevOps
    "ci-cd",
    "pipeline",
    "github-actions",
    "jenkins",
    "gitlab-ci",
    "deployment-strategies",
    "blue-green",
    "canary",
    "rolling-updates",

    // Git & Version Control
    "git",
    "merge",
    "rebase",
    "cherry-pick",
    "branching",
    "pull-requests",
    "conflict-resolution",

    // Performance & Web Vitals
    "performance",
    "web-vitals",
    "lighthouse",
    "lcp",
    "fid",
    "cls",
    "ttfb",
    "memoization",
    "prefetching",
    "preloading",
    "bundle-analysis",

    // Monitoring & Observability
    "monitoring",
    "observability",
    "error-tracking",
    "logging",
    "tracing",
    "sentry",
    "datadog",
    "prometheus",
    "grafana",
    "apm",

    // Architecture & Design Patterns
    "system-design",
    "microservices",
    "service-discovery",
    "api-gateway",
    "event-driven",
    "message-queues",
    "circuit-breaker",
    "saga-pattern",
    "cqrs",
    "event-sourcing",
    "domain-driven-design",
    "clean-architecture",
    "hexagonal-architecture",
    "design-patterns",
    "solid",
    "oop",
    "dry",
    "kiss",
    "yagni",
    "service-mesh",
    "load-balancing",
    "scalability",
    "high-availability",
    "fault-tolerance",
    "eventual-consistency",

    // Concurrency & Distributed Systems
    "race-conditions",
    "concurrency",
    "deadlocks",
    "mutex",
    "semaphores",
    "web-workers",

    // Debugging
    "debugging",
    "code-review",
    "technical-debt",

    // AI & Modern Development
    "ai",
    "llm",
    "copilot",
    "code-generation",

    // Behavioral & Soft Skills
    "behavioral",
    "leadership",
    "communication",
    "problem-solving",
    "teamwork",

    // Algorithms & Data Structures
    "time-complexity",
    "space-complexity",
    "big-o",
    "data-structures",
    "hash-tables",
    "arrays",
    "linked-lists",
    "stacks",
    "queues",
    "trees",
    "binary-trees",
    "binary-search-trees",
    "heaps",
    "tries",
    "graphs",
    "sorting",
    "quicksort",
    "mergesort",
    "heapsort",
    "searching",
    "binary-search",
    "recursion",
] as const;

export const ValidTag = z.enum(validTags);

export type ValidTag = z.infer<typeof ValidTag>;
export const _Tag = ValidTag.enum;
