import { Category, Level, ValidTag } from "../../../db";
import type { QuestionForCategoryAndLevel } from "../../../lib/types";

export const mid: QuestionForCategoryAndLevel<
    typeof Category.enum.behavioral,
    typeof Level.enum.mid
>[] = [
    {
        text: "What's the most complicated feature or project you've ever worked on?",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.behavioral],
        answers: [],
    },
    {
        text: "What's your proudest accomplishment (of something you built)?",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.behavioral],
        answers: [],
    },

    // AI in Development
    {
        text: "How do you use AI tools like GitHub Copilot or ChatGPT in your workflow?",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.ai, ValidTag.enum.behavioral],
        answers: [],
    },
    {
        text: "What are the limitations of AI code generation tools?",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.ai, ValidTag.enum.behavioral],
        answers: [],
    },
    {
        text: "How do you evaluate AI-generated code for quality and security?",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.ai, ValidTag.enum.behavioral, ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What is prompt engineering?",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.ai],
        answers: [],
    },
    {
        text: "How has AI changed your development process?",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.ai, ValidTag.enum.behavioral],
        answers: [],
    },
    {
        text: "What tasks are AI tools good/bad at?",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.ai, ValidTag.enum.behavioral],
        answers: [],
    },
    {
        text: "How do you balance using AI tools with learning fundamentals?",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.ai, ValidTag.enum.behavioral],
        answers: [],
    },
    {
        text: "What ethical considerations exist when using AI in development?",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.ai, ValidTag.enum.behavioral],
        answers: [],
    },

    // Behavioral/Project-Specific
    {
        text: "Tell me about a challenging project you worked on",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.behavioral],
        answers: [],
    },
    {
        text: "How do you handle conflicts in a team?",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.behavioral],
        answers: [],
    },
    {
        text: "How do you prioritize tasks when everything is urgent?",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.behavioral],
        answers: [],
    },
    {
        text: "Tell me about a time you had to learn a new technology quickly",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.behavioral],
        answers: [],
    },
    {
        text: "How do you stay up-to-date with new technologies?",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.behavioral],
        answers: [],
    },
    {
        text: "What's your approach to code review?",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.behavioral, ValidTag.enum["code-review"]],
        answers: [],
    },
    {
        text: "How do you handle technical debt?",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.behavioral, ValidTag.enum["technical-debt"]],
        answers: [],
    },
    {
        text: "Tell me about a mistake you made and how you handled it",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.behavioral],
        answers: [],
    },
    {
        text: "How do you mentor junior developers?",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.behavioral],
        answers: [],
    },
    {
        text: "What's your ideal development environment/workflow?",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.behavioral],
        answers: [],
    },
    {
        text: "How do you handle tight deadlines?",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.behavioral],
        answers: [],
    },
    {
        text: "Tell me about a time you had to make a technical decision with incomplete information",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.behavioral],
        answers: [],
    },
    {
        text: "How do you approach performance optimization?",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.behavioral, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What's your debugging process?",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.behavioral, ValidTag.enum.debugging],
        answers: [],
    },
    {
        text: "How do you ensure code quality in your projects?",
        level: Level.enum.mid,
        category: Category.enum.behavioral,
        tags: [ValidTag.enum.behavioral],
        answers: [],
    },
];
