import { Category, Level, ValidTag } from "../../../db";
import type { QuestionForCategoryAndLevel } from "../../../lib/types";

export const mid: QuestionForCategoryAndLevel<
    typeof Category.enum.backend,
    typeof Level.enum.mid
>[] = [
    // Node.js
    {
        text: "What is Node.js and how does its event-driven architecture work?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nodejs, ValidTag.enum["event-driven"]],
        answers: [],
    },
    {
        text: "What is the difference between process.nextTick() and setImmediate()?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nodejs, ValidTag.enum["event-loop"]],
        answers: [],
    },
    {
        text: "What are streams in Node.js and when would you use them?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nodejs, ValidTag.enum.streams],
        answers: [],
    },
    {
        text: "What is the difference between spawning a child process and using worker threads?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nodejs, ValidTag.enum["child-processes"]],
        answers: [],
    },
    {
        text: "How do you handle uncaught exceptions in Node.js?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nodejs, ValidTag.enum["error-handling"]],
        answers: [],
    },
    {
        text: "What is backpressure and how do you handle it?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nodejs, ValidTag.enum.streams],
        answers: [],
    },
    {
        text: "What are buffers in Node.js?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nodejs, ValidTag.enum.buffers],
        answers: [],
    },
    {
        text: "What is the difference between require and import?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nodejs, ValidTag.enum.modules],
        answers: [],
    },
    {
        text: "How does the module resolution algorithm work?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nodejs, ValidTag.enum.modules],
        answers: [],
    },
    {
        text: "What is the cluster module and how do you scale Node.js?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nodejs, ValidTag.enum.cluster, ValidTag.enum.scalability],
        answers: [],
    },
    {
        text: "What are environment variables and how do you manage them?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nodejs],
        answers: [],
    },
    {
        text: "What is the event emitter pattern?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nodejs, ValidTag.enum["event-emitter"]],
        answers: [],
    },
    {
        text: "What is libuv and how does it relate to Node.js?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nodejs, ValidTag.enum["event-loop"]],
        answers: [],
    },

    // Express
    {
        text: "How do you handle errors in Express?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.express, ValidTag.enum["error-handling"]],
        answers: [],
    },
    {
        text: "How do you structure a large Express application?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.express],
        answers: [],
    },
    {
        text: "How do you implement rate limiting in Express?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.express, ValidTag.enum["rate-limiting"]],
        answers: [],
    },
    {
        text: "What are routers in Express and how do you modularize routes?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.express],
        answers: [],
    },
    {
        text: "How do you handle file uploads in Express?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.express],
        answers: [],
    },
    {
        text: "What is CORS middleware and how do you configure it?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.express, ValidTag.enum.cors],
        answers: [],
    },

    // REST APIs
    {
        text: "How do you version APIs?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum["rest-api"], ValidTag.enum["api-versioning"]],
        answers: [],
    },
    {
        text: "What is HATEOAS and when is it useful?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum["rest-api"]],
        answers: [],
    },
    {
        text: "How do you design error responses?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum["rest-api"], ValidTag.enum["error-handling"]],
        answers: [],
    },
    {
        text: "How do you handle pagination and what are the tradeoffs between offset and cursor-based?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum["rest-api"], ValidTag.enum.pagination],
        answers: [],
    },
    {
        text: "What is rate limiting and how would you implement it?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum["rest-api"], ValidTag.enum["rate-limiting"]],
        answers: [],
    },
    {
        text: "How do you document APIs?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum["rest-api"], ValidTag.enum["api-design"]],
        answers: [],
    },
    {
        text: "How do you handle filtering and sorting?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum["rest-api"]],
        answers: [],
    },
    {
        text: "What is content negotiation?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum["rest-api"]],
        answers: [],
    },
    {
        text: "What are ETags and conditional requests?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum["rest-api"], ValidTag.enum.etag, ValidTag.enum.caching],
        answers: [],
    },

    // GraphQL
    {
        text: "What is GraphQL and how does it differ from REST?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.graphql, ValidTag.enum["rest-api"]],
        answers: [],
    },
    {
        text: "What are queries, mutations, and subscriptions?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.graphql],
        answers: [],
    },
    {
        text: "What is the GraphQL schema and type system?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.graphql],
        answers: [],
    },
    {
        text: "How would you handle the n+1 problem in GraphQL?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.graphql, ValidTag.enum["n-plus-one"], ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What are resolvers and how do they work?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.graphql],
        answers: [],
    },
    {
        text: "What is the DataLoader pattern?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.graphql, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "How do you handle authentication and authorization in GraphQL?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.graphql, ValidTag.enum.auth, ValidTag.enum.authorization],
        answers: [],
    },
    {
        text: "What are fragments and when would you use them?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.graphql],
        answers: [],
    },
    {
        text: "What are directives in GraphQL?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.graphql],
        answers: [],
    },
    {
        text: "How do you handle errors in GraphQL?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.graphql, ValidTag.enum["error-handling"]],
        answers: [],
    },
    {
        text: "What is introspection and when should you disable it?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.graphql, ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What are input types vs output types?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.graphql],
        answers: [],
    },
    {
        text: "How do you implement pagination in GraphQL?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.graphql, ValidTag.enum.pagination],
        answers: [],
    },

    // WebSockets
    {
        text: "What are WebSockets and how do they differ from HTTP?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.websockets],
        answers: [],
    },
    {
        text: "What is the WebSocket handshake?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.websockets],
        answers: [],
    },
    {
        text: "What is Socket.io and how does it differ from native WebSockets?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.websockets],
        answers: [],
    },
    {
        text: "How do you handle WebSocket authentication?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.websockets, ValidTag.enum.auth],
        answers: [],
    },
    {
        text: "What are rooms and namespaces in Socket.io?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.websockets],
        answers: [],
    },
    {
        text: "What is the difference between WebSockets and Server-Sent Events?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.websockets],
        answers: [],
    },
    {
        text: "How do you handle reconnection and connection state?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.websockets],
        answers: [],
    },
    {
        text: "What are heartbeats and ping/pong frames?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.websockets],
        answers: [],
    },

    // NestJS
    {
        text: "What is NestJS and how does it differ from Express?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nestjs, ValidTag.enum.express],
        answers: [],
    },
    {
        text: "What are modules, controllers, and providers in NestJS?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nestjs],
        answers: [],
    },
    {
        text: "How does dependency injection work in NestJS?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nestjs, ValidTag.enum["dependency-injection"]],
        answers: [],
    },
    {
        text: "What are guards and how do you implement authorization?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nestjs, ValidTag.enum.guards, ValidTag.enum.authorization],
        answers: [],
    },
    {
        text: "What are interceptors and when would you use them?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nestjs, ValidTag.enum.interceptors],
        answers: [],
    },
    {
        text: "What are pipes and how do you handle validation?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nestjs, ValidTag.enum.pipes, ValidTag.enum.validation],
        answers: [],
    },
    {
        text: "What are exception filters?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nestjs, ValidTag.enum["error-handling"]],
        answers: [],
    },
    {
        text: "How do you handle configuration in NestJS?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nestjs],
        answers: [],
    },
    {
        text: "What is the difference between @Injectable() and @Controller()?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nestjs],
        answers: [],
    },
    {
        text: "How do you implement WebSockets in NestJS?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nestjs, ValidTag.enum.websockets],
        answers: [],
    },
    {
        text: "How do you structure a large NestJS application?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nestjs],
        answers: [],
    },
    {
        text: "What are custom decorators and how do you create them?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.nestjs, ValidTag.enum.decorators],
        answers: [],
    },

    // Serverless
    {
        text: "What is serverless architecture and what are its tradeoffs?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.serverless],
        answers: [],
    },
    {
        text: "What is cold start and how do you mitigate it?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.serverless, ValidTag.enum.lambda, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "How do you handle state in serverless functions?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.serverless],
        answers: [],
    },
    {
        text: "What is the difference between AWS Lambda and serverless containers?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.serverless, ValidTag.enum.lambda, ValidTag.enum.aws],
        answers: [],
    },
    {
        text: "How do you handle database connections in serverless?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.serverless],
        answers: [],
    },
    {
        text: "What are edge functions and when would you use them?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.serverless],
        answers: [],
    },
    {
        text: "How do you handle long-running tasks in serverless?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.serverless],
        answers: [],
    },
    {
        text: "What is the serverless framework?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.serverless],
        answers: [],
    },
    {
        text: "How do you handle local development for serverless?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.serverless],
        answers: [],
    },
    {
        text: "What are the cost implications of serverless vs traditional servers?",
        level: Level.enum.mid,
        category: Category.enum.backend,
        tags: [ValidTag.enum.serverless],
        answers: [],
    },
];
