import { Category, Level, ValidTag } from "../../../db";
import type { QuestionForCategoryAndLevel } from "../../../lib/types";

export const mid: QuestionForCategoryAndLevel<
    typeof Category.enum.security,
    typeof Level.enum.mid
>[] = [
    // Authentication and Authorization
    {
        text: "What is the difference between authentication and authorization?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.auth, ValidTag.enum.authorization],
        answers: [],
    },
    {
        text: "What are JWTs and how do they work?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.jwt, ValidTag.enum.auth],
        answers: [],
    },
    {
        text: "What is the structure of a JWT?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.jwt],
        answers: [],
    },
    {
        text: "What are refresh tokens and why are they needed?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.jwt, ValidTag.enum["refresh-tokens"], ValidTag.enum.auth],
        answers: [],
    },
    {
        text: "What is the difference between access tokens and refresh tokens?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.jwt, ValidTag.enum["refresh-tokens"]],
        answers: [],
    },
    {
        text: "How does OAuth 2.0 work?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.oauth, ValidTag.enum.auth],
        answers: [],
    },
    {
        text: "What are the different OAuth grant types and when do you use each?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.oauth],
        answers: [],
    },
    {
        text: "What is OIDC (OpenID Connect) and how does it relate to OAuth?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.oauth, ValidTag.enum.auth],
        answers: [],
    },
    {
        text: "What is the difference between sessions and JWTs?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.jwt, ValidTag.enum["session-management"], ValidTag.enum.auth],
        answers: [],
    },
    {
        text: "When would you choose sessions over JWTs?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.jwt, ValidTag.enum["session-management"]],
        answers: [],
    },
    {
        text: "How do you implement token rotation?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.jwt, ValidTag.enum["refresh-tokens"]],
        answers: [],
    },
    {
        text: "What is PKCE and why is it important for mobile/SPA apps?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.oauth],
        answers: [],
    },
    {
        text: "How do you store tokens securely on the client?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.jwt, ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What is token revocation and how do you implement it?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.jwt, ValidTag.enum.auth],
        answers: [],
    },
    {
        text: "What are scopes and claims in OAuth?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.oauth],
        answers: [],
    },
    {
        text: "What is multi-factor authentication and how do you implement it?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.auth],
        answers: [],
    },
    {
        text: "What are magic links and passwordless authentication?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.auth],
        answers: [],
    },
    {
        text: "What is SSO (Single Sign-On) and how do you implement it?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.auth],
        answers: [],
    },
    {
        text: "What is SAML and how does it differ from OAuth?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.auth, ValidTag.enum.oauth],
        answers: [],
    },
    {
        text: "How do you handle authentication in microservices?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.auth, ValidTag.enum.microservices],
        answers: [],
    },

    // Security
    {
        text: "What is CSRF and how do you prevent it?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.csrf, ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What is XSS and what are the different types?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.xss, ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What is SQL injection and how do you prevent it?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum["sql-injection"], ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What is CORS and why does it exist?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.cors, ValidTag.enum.security],
        answers: [],
    },
    {
        text: "How do you configure CORS properly?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.cors, ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What are security headers and which ones should you use?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What is Content Security Policy?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What is HTTPS and how does TLS work?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.security],
        answers: [],
    },
    {
        text: "How do you securely store passwords?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum["password-hashing"], ValidTag.enum.bcrypt, ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What is bcrypt and why is it preferred for password hashing?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.bcrypt, ValidTag.enum["password-hashing"]],
        answers: [],
    },
    {
        text: "What is the difference between encryption and hashing?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What is the difference between symmetric and asymmetric encryption?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What are common OWASP vulnerabilities?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What is rate limiting and how do you implement it?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum["rate-limiting"], ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What is input validation and sanitization?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.validation, ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What is clickjacking and how do you prevent it?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What are secure cookies and what flags should you set?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.security, ValidTag.enum["session-management"]],
        answers: [],
    },
    {
        text: "How do you handle secrets management?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.security],
        answers: [],
    },
    {
        text: "What is the principle of least privilege?",
        level: Level.enum.mid,
        category: Category.enum.security,
        tags: [ValidTag.enum.security, ValidTag.enum.authorization],
        answers: [],
    },
];
