import { Category, Level, ValidTag } from "../../../db";
import type { QuestionForCategoryAndLevel } from "../../../lib/types";

export const midAdvanced: QuestionForCategoryAndLevel<
    typeof Category.enum.frontend,
    typeof Level.enum["mid-advanced"]
>[] = [
    // JavaScript
    {
        text: "What are WeakMap and WeakSet and when would you use them?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.javascript, ValidTag.enum.weakmap, ValidTag.enum.weakset],
        answers: [],
    },
    {
        text: "What is tail call optimization?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.javascript, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What is the Temporal Dead Zone?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.javascript, ValidTag.enum.hoisting, ValidTag.enum.scope],
        answers: [],
    },

    // TypeScript
    {
        text: "What are conditional types and how do you use them?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.typescript, ValidTag.enum["conditional-types"], ValidTag.enum.types],
        answers: [],
    },
    {
        text: "What are mapped types?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.typescript, ValidTag.enum["mapped-types"], ValidTag.enum.types],
        answers: [],
    },
    {
        text: "What is the infer keyword and how do you use it?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.typescript, ValidTag.enum["conditional-types"]],
        answers: [],
    },
    {
        text: "What are template literal types?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.typescript, ValidTag.enum.types],
        answers: [],
    },
    {
        text: "What is type widening and how do you prevent it?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.typescript, ValidTag.enum.types],
        answers: [],
    },
    {
        text: "What are function overloads in TypeScript?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.typescript, ValidTag.enum.types],
        answers: [],
    },
    {
        text: "What is the satisfies operator and when would you use it?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.typescript, ValidTag.enum.types],
        answers: [],
    },
    {
        text: "What are branded types and how do you implement them?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.typescript, ValidTag.enum.types],
        answers: [],
    },

    // CSS
    {
        text: "What are the tradeoffs between CSS Modules vs Tailwind vs CSS-in-JS?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.css, ValidTag.enum["css-modules"], ValidTag.enum.tailwind, ValidTag.enum["css-in-js"]],
        answers: [],
    },
    {
        text: "How do you handle dark mode in Tailwind?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.tailwind, ValidTag.enum.css],
        answers: [],
    },
    {
        text: "What are Tailwind plugins and how do you use them?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.tailwind],
        answers: [],
    },
    {
        text: "How do you handle animations in Tailwind?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.tailwind, ValidTag.enum.animations],
        answers: [],
    },
    {
        text: "What are CSS custom properties and how do they differ from Sass variables?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.css, ValidTag.enum.sass],
        answers: [],
    },

    // React Hooks Advanced
    {
        text: "What's the difference between useCallback and useMemo? When would you use each?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.hooks, ValidTag.enum.performance, ValidTag.enum.memoization, ValidTag.enum.useCallback, ValidTag.enum.useMemo],
        answers: [],
    },
    {
        text: "What is useImperativeHandle and when is it appropriate?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.hooks],
        answers: [],
    },
    {
        text: "What is useDeferredValue and how does it differ from debouncing?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.hooks, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What is useTransition and when would you use it?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.hooks, ValidTag.enum["concurrent-mode"]],
        answers: [],
    },
    {
        text: "What is useSyncExternalStore and when do you need it?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.hooks],
        answers: [],
    },

    // React Advanced
    {
        text: "What is React's reconciliation algorithm and how does it decide what to re-render?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.reconciliation, ValidTag.enum["virtual-dom"], ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What causes infinite re-render loops and how do you debug them?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.debugging],
        answers: [],
    },
    {
        text: "What is StrictMode and why does it cause double-rendering?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react],
        answers: [],
    },
    {
        text: "What are portals and when would you use them?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.portals],
        answers: [],
    },
    {
        text: "What is React.memo and when does it actually improve performance?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.performance, ValidTag.enum.memoization],
        answers: [],
    },
    {
        text: "What are render props and when would you use them over hooks?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react],
        answers: [],
    },
    {
        text: "What are compound components and how do you implement them?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum["design-patterns"]],
        answers: [],
    },
    {
        text: "What is the children prop and how do you manipulate it?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react],
        answers: [],
    },
    {
        text: "What is React.lazy and how do you use it with Suspense?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.suspense, ValidTag.enum["lazy-loading"], ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What is forwardRef and when do you need it?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react],
        answers: [],
    },
    {
        text: "What are custom hooks and what makes a good custom hook?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.hooks, ValidTag.enum["custom-hooks"]],
        answers: [],
    },
    {
        text: "What is the difference between optimistic and pessimistic UI updates?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react],
        answers: [],
    },
    {
        text: "What is hydration and what causes hydration mismatches?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.ssr, ValidTag.enum.nextjs],
        answers: [],
    },
    {
        text: "What are concurrent features in React 18?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum["concurrent-mode"]],
        answers: [],
    },
    {
        text: "What is automatic batching in React 18?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.performance],
        answers: [],
    },

    // State Management
    {
        text: "When would you choose Redux vs React Context vs Zustand vs TanStack Query?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.redux, ValidTag.enum.zustand, ValidTag.enum["context-api"], ValidTag.enum["tanstack-query"], ValidTag.enum.react],
        answers: [],
    },
    {
        text: "What are Redux Toolkit slices and how do they simplify Redux?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.redux, ValidTag.enum["redux-toolkit"]],
        answers: [],
    },
    {
        text: "What is Redux middleware and how does Redux Thunk differ from Redux Saga?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.redux, ValidTag.enum["redux-toolkit"]],
        answers: [],
    },
    {
        text: "What is the difference between normalized and denormalized state?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react],
        answers: [],
    },
    {
        text: "What are selectors and why are they important for performance?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.redux, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What is state colocation and why does it matter?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react],
        answers: [],
    },

    // TanStack Query Advanced
    {
        text: "What is optimistic updates and how do you implement them?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum["tanstack-query"]],
        answers: [],
    },
    {
        text: "What is infinite queries and how do you implement pagination?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum["tanstack-query"]],
        answers: [],
    },
    {
        text: "What is prefetching and when would you use it?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum["tanstack-query"], ValidTag.enum.performance, ValidTag.enum.prefetching],
        answers: [],
    },
    {
        text: "What is the difference between refetch and invalidate?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum["tanstack-query"]],
        answers: [],
    },
    {
        text: "How does garbage collection work in TanStack Query?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum["tanstack-query"], ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What is placeholder data vs initial data?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum["tanstack-query"]],
        answers: [],
    },
    {
        text: "How do you handle offline support?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum["tanstack-query"]],
        answers: [],
    },

    // Next.js Advanced
    {
        text: "What is the _document.js file and when would you customize it?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum["pages-router"]],
        answers: [],
    },
    {
        text: "How do you handle redirects and rewrites?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs],
        answers: [],
    },
    {
        text: "What is middleware in Next.js and what are valid use cases?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum.middleware],
        answers: [],
    },
    {
        text: "How do you debug large Next.js bundle sizes?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum.debugging, ValidTag.enum.bundling],
        answers: [],
    },
    {
        text: "What is the difference between fallback: false, fallback: true, and fallback: 'blocking'?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum["pages-router"], ValidTag.enum.ssg],
        answers: [],
    },
    {
        text: "What is getInitialProps and why is it generally discouraged?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum["pages-router"]],
        answers: [],
    },
    {
        text: "How do you handle authentication in the Pages Router?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum["pages-router"], ValidTag.enum.auth],
        answers: [],
    },
    {
        text: "How does the App Router differ from the Pages Router?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum["app-router"], ValidTag.enum["pages-router"]],
        answers: [],
    },
    {
        text: "What are Server Components vs Client Components?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum["app-router"], ValidTag.enum["server-components"], ValidTag.enum.rsc],
        answers: [],
    },
    {
        text: "What is the use client directive and when do you need it?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum["app-router"], ValidTag.enum["server-components"]],
        answers: [],
    },
    {
        text: "What are loading.js and error.js files?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum["app-router"]],
        answers: [],
    },
    {
        text: "How does the App Router handle layouts and nested layouts?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum["app-router"]],
        answers: [],
    },
    {
        text: "What is the metadata API in the App Router?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum["app-router"], ValidTag.enum.seo],
        answers: [],
    },
    {
        text: "How does caching work in the App Router?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum["app-router"], ValidTag.enum.caching, ValidTag.enum.performance],
        answers: [],
    },

    // React Native Advanced
    {
        text: "What are native modules and when would you create one?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum["react-native"]],
        answers: [],
    },
    {
        text: "What is the new architecture in React Native (Fabric, TurboModules, JSI)?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum["react-native"]],
        answers: [],
    },
    {
        text: "What are performance considerations specific to React Native?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum["react-native"], ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "How do you handle deep linking in React Native?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum["react-native"], ValidTag.enum.routing],
        answers: [],
    },
    {
        text: "What is CodePush and how does over-the-air updates work?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum["react-native"]],
        answers: [],
    },
    {
        text: "How do you handle gestures and animations in React Native?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum["react-native"], ValidTag.enum.animations],
        answers: [],
    },

    // Accessibility Advanced
    {
        text: "What is the accessibility tree?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.accessibility, ValidTag.enum.a11y],
        answers: [],
    },
    {
        text: "How do you make a custom dropdown accessible?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.accessibility, ValidTag.enum.aria],
        answers: [],
    },
    {
        text: "What are skip links?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.accessibility],
        answers: [],
    },
    {
        text: "How do you test for accessibility?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.accessibility, ValidTag.enum.testing],
        answers: [],
    },
    {
        text: "What is keyboard navigation and how do you implement it?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.accessibility, ValidTag.enum["keyboard-navigation"]],
        answers: [],
    },
    {
        text: "What are ARIA live regions?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.accessibility, ValidTag.enum.aria],
        answers: [],
    },
    {
        text: "What is color contrast and how do you check it?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.accessibility, ValidTag.enum.wcag],
        answers: [],
    },

    // Testing Advanced
    {
        text: "How do you test components that fetch data?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.testing, ValidTag.enum.rtl, ValidTag.enum.react],
        answers: [],
    },
    {
        text: "What is act() and when do you need it?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.testing, ValidTag.enum.rtl, ValidTag.enum.react],
        answers: [],
    },
    {
        text: "How do you test custom hooks?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.testing, ValidTag.enum.rtl, ValidTag.enum.react, ValidTag.enum.hooks],
        answers: [],
    },
    {
        text: "How do you test error boundaries?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.testing, ValidTag.enum.rtl, ValidTag.enum.react],
        answers: [],
    },
    {
        text: "What is screen and why should you use it?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.testing, ValidTag.enum.rtl],
        answers: [],
    },
    {
        text: "How do you debug failing tests?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.testing, ValidTag.enum.debugging],
        answers: [],
    },

    // Git Advanced
    {
        text: "What is interactive rebase?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.git, ValidTag.enum.rebase],
        answers: [],
    },
    {
        text: "What is git bisect?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.git, ValidTag.enum.debugging],
        answers: [],
    },
    {
        text: "What are Git submodules?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.git],
        answers: [],
    },
    {
        text: "What is force push and when is it safe to use?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.git],
        answers: [],
    },
    {
        text: "What is squashing commits and when would you do it?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.git],
        answers: [],
    },

    // Performance Advanced
    {
        text: "What is the Performance panel and how do you identify bottlenecks?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.debugging, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What is the Memory panel and how do you detect memory leaks?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.debugging, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What are React DevTools and how do you use them?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.debugging],
        answers: [],
    },
    {
        text: "What are some debugging tools you use?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.debugging],
        answers: [],
    },
    {
        text: "What is the difference between LCP, FID/INP, and CLS?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.performance, ValidTag.enum["web-vitals"], ValidTag.enum.lcp, ValidTag.enum.fid, ValidTag.enum.cls],
        answers: [],
    },
    {
        text: "What are source maps and how do they work?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.debugging],
        answers: [],
    },
    {
        text: "How do you profile JavaScript performance?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.performance, ValidTag.enum.debugging],
        answers: [],
    },
    {
        text: "What is the difference between client-side and server-side profiling?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.performance, ValidTag.enum.debugging],
        answers: [],
    },
    {
        text: "How do you identify and fix memory leaks?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.performance, ValidTag.enum.debugging],
        answers: [],
    },
    {
        text: "What causes render blocking and how do you avoid it?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What is the critical rendering path?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.performance],
        answers: [],
    },

    // Bundle Sizing
    {
        text: "How would you debug large bundle sizes?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.debugging, ValidTag.enum.bundling, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What tools do you use to analyze bundle size?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.bundling, ValidTag.enum.performance, ValidTag.enum["bundle-analysis"]],
        answers: [],
    },
    {
        text: "What is webpack-bundle-analyzer?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.webpack, ValidTag.enum.bundling, ValidTag.enum["bundle-analysis"]],
        answers: [],
    },
    {
        text: "What is the difference between named exports and default exports for tree shaking?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum["tree-shaking"], ValidTag.enum.bundling, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "How do you optimize third-party library imports?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.bundling, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What is dynamic imports and how do they help bundle size?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.bundling, ValidTag.enum["code-splitting"], ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "How do you measure and track bundle size over time?",
        level: Level.enum["mid-advanced"],
        category: Category.enum.frontend,
        tags: [ValidTag.enum.bundling, ValidTag.enum.performance, ValidTag.enum["bundle-analysis"]],
        answers: [],
    },
];
