import { Category, Level, ValidTag } from "../../../db";
import type { QuestionForCategoryAndLevel } from "../../../lib/types";

export const mid: QuestionForCategoryAndLevel<
    typeof Category.enum.frontend,
    typeof Level.enum.mid
>[] = [
    // JavaScript
    {
        text: "What is the event loop and how does it handle asynchronous operations?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.javascript, ValidTag.enum["event-loop"], ValidTag.enum["async-await"]],
        answers: [],
    },
    {
        text: "What are Promises and how do they differ from async/await?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.javascript, ValidTag.enum.promises, ValidTag.enum["async-await"]],
        answers: [],
    },
    {
        text: "What is event delegation and why is it useful?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.javascript],
        answers: [],
    },
    {
        text: "What are generators and iterators?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.javascript, ValidTag.enum.generators, ValidTag.enum.iterators],
        answers: [],
    },
    {
        text: "What are Web Workers and when would you use them?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.javascript, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What is prototype inheritance and how does it work?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.javascript, ValidTag.enum.prototypes],
        answers: [],
    },
    {
        text: "What is the module pattern and how do ES modules differ from CommonJS?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.javascript, ValidTag.enum.modules],
        answers: [],
    },
    {
        text: "What is optional chaining and nullish coalescing?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.javascript],
        answers: [],
    },
    {
        text: "What is debouncing vs throttling and when would you use each?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.javascript, ValidTag.enum.performance],
        answers: [],
    },

    // TypeScript
    {
        text: "What are generics in TypeScript and how do you use them?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.typescript, ValidTag.enum.generics],
        answers: [],
    },
    {
        text: "What are union types and discriminated unions?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.typescript, ValidTag.enum.types],
        answers: [],
    },
    {
        text: "What is type narrowing and how does TypeScript infer types?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.typescript, ValidTag.enum["type-guards"], ValidTag.enum.types],
        answers: [],
    },
    {
        text: "What are utility types and when would you use Partial, Pick, Omit, Record, Required, or Readonly?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.typescript, ValidTag.enum["utility-types"]],
        answers: [],
    },
    {
        text: "What is the never type and when is it used?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.typescript, ValidTag.enum.types],
        answers: [],
    },
    {
        text: "What are declaration files and when do you need them?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.typescript],
        answers: [],
    },
    {
        text: "What are index signatures and when would you use them?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.typescript, ValidTag.enum.types],
        answers: [],
    },

    // CSS
    {
        text: "What is the critical rendering path and how does CSS block rendering?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.css, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What causes layout thrashing and how do you avoid it?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.css, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "How do you compose styles in CSS Modules?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.css, ValidTag.enum["css-modules"]],
        answers: [],
    },
    {
        text: "How do you create custom utilities and components in Tailwind?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.tailwind],
        answers: [],
    },
    {
        text: "What is the @apply directive and when should you avoid it?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.tailwind],
        answers: [],
    },
    {
        text: "How does Tailwind's JIT compiler work?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.tailwind],
        answers: [],
    },

    // React Core
    {
        text: "What is the React Virtual DOM and why is it important?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum["virtual-dom"]],
        answers: [],
    },
    {
        text: "What are synthetic events in React?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum["synthetic-events"]],
        answers: [],
    },
    {
        text: "How do you handle forms in React and what are the tradeoffs of different approaches?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.forms],
        answers: [],
    },

    // React Hooks
    {
        text: "What is useState and how does state batching work?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.hooks, ValidTag.enum.useState],
        answers: [],
    },
    {
        text: "What is useEffect and what are its cleanup patterns?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.hooks, ValidTag.enum.useEffect],
        answers: [],
    },
    {
        text: "What is the difference between useEffect and useLayoutEffect?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.hooks, ValidTag.enum.useEffect],
        answers: [],
    },
    {
        text: "What is useRef and what are its use cases beyond DOM references?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.hooks, ValidTag.enum.useRef],
        answers: [],
    },
    {
        text: "What is useCallback and when should you use it?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.hooks, ValidTag.enum.useCallback, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What is useMemo and when does it actually help performance?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.hooks, ValidTag.enum.useMemo, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What is the difference between useCallback and useMemo?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.hooks, ValidTag.enum.useCallback, ValidTag.enum.useMemo],
        answers: [],
    },
    {
        text: "What is useContext and what are its performance implications?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.hooks, ValidTag.enum.useContext, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What is useReducer and when would you use it over useState?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.hooks, ValidTag.enum.useReducer, ValidTag.enum.useState],
        answers: [],
    },
    {
        text: "What is useId and why was it introduced?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.hooks],
        answers: [],
    },

    // State Management
    {
        text: "What is Redux and how does the data flow work?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.redux, ValidTag.enum.react],
        answers: [],
    },
    {
        text: "What is Zustand and why would you choose it over Redux?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.zustand, ValidTag.enum.react],
        answers: [],
    },
    {
        text: "What are the performance implications of React Context?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum["context-api"], ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "How do you structure global state vs server state vs local state?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react],
        answers: [],
    },
    {
        text: "How do you handle derived state?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.react, ValidTag.enum.state],
        answers: [],
    },

    // TanStack Query
    {
        text: "What is TanStack Query and what problems does it solve?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum["tanstack-query"], ValidTag.enum.react],
        answers: [],
    },
    {
        text: "What is the difference between useQuery and useMutation?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum["tanstack-query"], ValidTag.enum.react],
        answers: [],
    },
    {
        text: "What is stale-while-revalidate and how does TanStack Query implement it?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum["tanstack-query"], ValidTag.enum.caching],
        answers: [],
    },
    {
        text: "How does query caching work in TanStack Query?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum["tanstack-query"], ValidTag.enum["query-cache"], ValidTag.enum.caching],
        answers: [],
    },
    {
        text: "What are query keys and how should you structure them?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum["tanstack-query"], ValidTag.enum["query-keys"]],
        answers: [],
    },
    {
        text: "What is query invalidation and when would you use it?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum["tanstack-query"]],
        answers: [],
    },
    {
        text: "How do you handle dependent queries?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum["tanstack-query"]],
        answers: [],
    },
    {
        text: "How do you handle error and loading states?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum["tanstack-query"], ValidTag.enum.react],
        answers: [],
    },

    // Next.js
    {
        text: "What is Next.js and what problems does it solve over plain React?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum.react],
        answers: [],
    },
    {
        text: "What is the difference between SSR, SSG, and ISR?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum.ssr, ValidTag.enum.ssg, ValidTag.enum.isr],
        answers: [],
    },
    {
        text: "When would you use server-side rendering vs client-side rendering?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum.ssr, ValidTag.enum.csr],
        answers: [],
    },
    {
        text: "How does Next.js handle routing?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum.routing],
        answers: [],
    },
    {
        text: "What is the _app.js file and what is it used for?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum["pages-router"]],
        answers: [],
    },
    {
        text: "How does Next.js handle image optimization?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What is next/head and how do you manage metadata?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum.seo],
        answers: [],
    },
    {
        text: "How do you handle environment variables in Next.js?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs],
        answers: [],
    },
    {
        text: "What is the public folder and how does static file serving work?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs],
        answers: [],
    },
    {
        text: "What is getStaticProps and when would you use it?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum["pages-router"], ValidTag.enum.ssg],
        answers: [],
    },
    {
        text: "What is getServerSideProps and what are its performance implications?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum["pages-router"], ValidTag.enum.ssr, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What is getStaticPaths and how does dynamic routing work?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum["pages-router"], ValidTag.enum["dynamic-routes"]],
        answers: [],
    },
    {
        text: "How do API routes work in the Pages Router?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum["pages-router"], ValidTag.enum["api-routes"]],
        answers: [],
    },
    {
        text: "What is ISR (Incremental Static Regeneration) and when would you use it?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.nextjs, ValidTag.enum.isr, ValidTag.enum.performance],
        answers: [],
    },

    // React Native
    {
        text: "What is React Native and how does it differ from React?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum["react-native"], ValidTag.enum.react],
        answers: [],
    },
    {
        text: "What is the bridge in React Native and how does it work?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum["react-native"]],
        answers: [],
    },
    {
        text: "What is the difference between React Native and Expo?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum["react-native"]],
        answers: [],
    },
    {
        text: "What are the core components in React Native?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum["react-native"]],
        answers: [],
    },
    {
        text: "What is the difference between StyleSheet and inline styles in React Native?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum["react-native"], ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "How do you handle platform-specific code in React Native?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum["react-native"]],
        answers: [],
    },
    {
        text: "What is the difference between FlatList and ScrollView?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum["react-native"], ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "How do you debug React Native applications?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum["react-native"], ValidTag.enum.debugging],
        answers: [],
    },
    {
        text: "How do you handle navigation in React Native?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum["react-native"], ValidTag.enum.routing],
        answers: [],
    },

    // Accessibility
    {
        text: "What is accessibility and why does it matter?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.accessibility, ValidTag.enum.a11y],
        answers: [],
    },
    {
        text: "What are WCAG guidelines?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.accessibility, ValidTag.enum.wcag],
        answers: [],
    },
    {
        text: "What is the difference between ARIA roles and semantic HTML?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.accessibility, ValidTag.enum.aria, ValidTag.enum["semantic-html"]],
        answers: [],
    },
    {
        text: "What is focus management and why does it matter?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.accessibility, ValidTag.enum["focus-management"]],
        answers: [],
    },

    // Testing
    {
        text: "What is React Testing Library and how does it differ from Enzyme?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.testing, ValidTag.enum.rtl, ValidTag.enum.react],
        answers: [],
    },
    {
        text: "What are the guiding principles of React Testing Library?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.testing, ValidTag.enum.rtl, ValidTag.enum.react],
        answers: [],
    },
    {
        text: "What are the different query methods and when do you use each?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.testing, ValidTag.enum.rtl],
        answers: [],
    },
    {
        text: "How do you test user interactions?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.testing, ValidTag.enum.rtl, ValidTag.enum.react],
        answers: [],
    },
    {
        text: "How do you test components with context?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.testing, ValidTag.enum.rtl, ValidTag.enum.react],
        answers: [],
    },
    {
        text: "How do you test components with hooks?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.testing, ValidTag.enum.rtl, ValidTag.enum.react, ValidTag.enum.hooks],
        answers: [],
    },

    // Git
    {
        text: "What is git reflog and when would you use it?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.git],
        answers: [],
    },
    {
        text: "What is the difference between git reset and git revert?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.git],
        answers: [],
    },
    {
        text: "What are the different modes of git reset (soft, mixed, hard)?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.git],
        answers: [],
    },
    {
        text: "What is cherry-picking?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.git, ValidTag.enum["cherry-pick"]],
        answers: [],
    },
    {
        text: "What is GitFlow vs trunk-based development?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.git, ValidTag.enum.branching],
        answers: [],
    },
    {
        text: "What are Git hooks?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.git],
        answers: [],
    },

    // Performance
    {
        text: "How would you optimize a slow loading page?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.performance, ValidTag.enum.debugging],
        answers: [],
    },
    {
        text: "What are Chrome DevTools and what are the key panels?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.debugging, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What is the Network panel and how do you use it to debug?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.debugging, ValidTag.enum.performance],
        answers: [],
    },
    {
        text: "What is Lighthouse and how do you use it?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.performance, ValidTag.enum.lighthouse],
        answers: [],
    },
    {
        text: "What is tree shaking and how does it work?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.performance, ValidTag.enum["tree-shaking"]],
        answers: [],
    },
    {
        text: "What is code splitting and how do you implement it?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.performance, ValidTag.enum["code-splitting"]],
        answers: [],
    },
    {
        text: "What is lazy loading and when should you use it?",
        level: Level.enum.mid,
        category: Category.enum.frontend,
        tags: [ValidTag.enum.performance, ValidTag.enum["lazy-loading"]],
        answers: [],
    },
];
